"""
IrsanAI-VERA — FastAPI REST Backend
api/server.py
"""

from __future__ import annotations
import os
import json
import asyncio
from pathlib import Path
from typing import Optional, List
from fastapi import FastAPI, BackgroundTasks, HTTPException
from pydantic import BaseModel

from core.investigation_cycle import InvestigationCycle
from core.ontology_loader import DomainOntology

app = FastAPI(title="IrsanAI-VERA API", version="0.4.0")

DATA_DIR = Path("data")
ONTOLOGIES_DIR = Path("ontologies")

class InvestigateRequest(BaseModel):
    ontology: str
    no_obsidian: bool = False

class SessionSummary(BaseModel):
    session_id: str
    timestamp: str
    domain: str
    belief: float
    verdict: str

def run_investigation(ontology_path: str, no_obsidian: bool):
    """Background task to run VERA investigation."""
    try:
        ontology = DomainOntology(Path(ontology_path))
        cycle = InvestigationCycle(
            ontology=ontology,
            skip_obsidian=no_obsidian
        )
        cycle.run()
    except Exception as e:
        print(f"Investigation error: {e}")

@app.post("/api/v1/investigate")
async def investigate(req: InvestigateRequest, background_tasks: BackgroundTasks):
    ontology_path = ONTOLOGIES_DIR / req.ontology
    if not ontology_path.exists():
        raise HTTPException(status_code=404, detail="Ontology not found")
    
    background_tasks.add_task(run_investigation, str(ontology_path), req.no_obsidian)
    return {"status": "started", "ontology": req.ontology}

@app.get("/api/v1/sessions", response_model=List[SessionSummary])
async def get_sessions():
    sessions = []
    if not DATA_DIR.exists():
        return []
        
    for report_file in DATA_DIR.glob("*_report.json"):
        try:
            with open(report_file, "r") as f:
                data = json.load(f)
                sessions.append(SessionSummary(
                    session_id=data["session_id"],
                    timestamp=data["timestamp"],
                    domain=data["domain"],
                    belief=data["belief_summary"]["current_belief"],
                    verdict=data["verdict"]["label"]
                ))
        except Exception:
            continue
    return sorted(sessions, key=lambda x: x.timestamp, reverse=True)

@app.get("/api/v1/sessions/{session_id}")
async def get_session_detail(session_id: str):
    report_file = DATA_DIR / f"{session_id}_report.json"
    if not report_file.exists():
        raise HTTPException(status_code=404, detail="Session not found")
    
    with open(report_file, "r") as f:
        return json.load(f)

@app.get("/api/v1/belief/current")
async def get_current_belief():
    sessions = await get_sessions()
    if not sessions:
        return {"belief": 0.0, "verdict": "No sessions", "health": 0.0}
    
    latest_session_id = sessions[0].session_id
    report = await get_session_detail(latest_session_id)
    
    return {
        "belief": report["belief_summary"]["current_belief"],
        "verdict": report["verdict"]["label"],
        "health": report.get("epistemic_audit", {}).get("health_score", 0.0)
    }

@app.get("/api/v1/health")
async def health():
    session_count = len(list(DATA_DIR.glob("*_report.json"))) if DATA_DIR.exists() else 0
    return {
        "status": "ok",
        "version": "0.4.0",
        "sessions": session_count
    }

@app.post("/api/v1/cip")
async def generate_cip(target: str):
    # This would normally generate a CIP markdown
    # For now, return a placeholder
    return {
        "document": f"# CIP for {target}\nGenerated by VERA API v0.4.0"
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
